/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GameType = IDL.Variant({
  'ConnectFour' : IDL.Null,
  'TicTacToe' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const GameState = IDL.Record({
  'winner' : IDL.Opt(IDL.Principal),
  'state' : IDL.Text,
  'currentTurn' : IDL.Principal,
  'player1' : IDL.Principal,
  'player2' : IDL.Principal,
  'gameType' : GameType,
});
export const Message = IDL.Record({
  'image_payload' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'text' : IDL.Text,
  'sender' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptGameChallenge' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearMessages' : IDL.Func([IDL.Principal], [], []),
  'createGameChallenge' : IDL.Func([IDL.Principal, GameType], [], []),
  'dropPresence' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGameState' : IDL.Func([IDL.Principal], [IDL.Opt(GameState)], ['query']),
  'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'numActivePeers' : IDL.Func([], [IDL.Nat], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, Message], [], []),
  'setGameWinner' : IDL.Func([IDL.Principal, IDL.Principal], [], []),
  'updateGameState' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'updatePresence' : IDL.Func([], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GameType = IDL.Variant({
    'ConnectFour' : IDL.Null,
    'TicTacToe' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const GameState = IDL.Record({
    'winner' : IDL.Opt(IDL.Principal),
    'state' : IDL.Text,
    'currentTurn' : IDL.Principal,
    'player1' : IDL.Principal,
    'player2' : IDL.Principal,
    'gameType' : GameType,
  });
  const Message = IDL.Record({
    'image_payload' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'text' : IDL.Text,
    'sender' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptGameChallenge' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearMessages' : IDL.Func([IDL.Principal], [], []),
    'createGameChallenge' : IDL.Func([IDL.Principal, GameType], [], []),
    'dropPresence' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGameState' : IDL.Func([IDL.Principal], [IDL.Opt(GameState)], ['query']),
    'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'numActivePeers' : IDL.Func([], [IDL.Nat], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, Message], [], []),
    'setGameWinner' : IDL.Func([IDL.Principal, IDL.Principal], [], []),
    'updateGameState' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updatePresence' : IDL.Func([], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };