/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GameState {
  'winner' : [] | [Principal],
  'state' : string,
  'currentTurn' : Principal,
  'player1' : Principal,
  'player2' : Principal,
  'gameType' : GameType,
}
export type GameType = { 'ConnectFour' : null } |
  { 'TicTacToe' : null };
export interface Message {
  'image_payload' : [] | [Uint8Array],
  'text' : string,
  'sender' : Principal,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptGameChallenge' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearMessages' : ActorMethod<[Principal], undefined>,
  'createGameChallenge' : ActorMethod<[Principal, GameType], undefined>,
  'dropPresence' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGameState' : ActorMethod<[Principal], [] | [GameState]>,
  'getMessages' : ActorMethod<[Principal], Array<Message>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'numActivePeers' : ActorMethod<[], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, Message], undefined>,
  'setGameWinner' : ActorMethod<[Principal, Principal], undefined>,
  'updateGameState' : ActorMethod<[Principal, string], undefined>,
  'updatePresence' : ActorMethod<[], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];